# Generated by Django 2.2.15 on 2021-10-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicchatroom',
            name='title',
            field=models.CharField(max_length=101, unique=True),
        ),
    ]
