# Generated by Django 2.2.15 on 2021-10-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_chat', '0002_auto_20211015_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicchatroom',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
