# Generated by Django 2.2.15 on 2021-10-16 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20211016_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomchatmessage',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roomchatmessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='PrivateChatRoom',
        ),
        migrations.DeleteModel(
            name='RoomChatMessage',
        ),
    ]
