# Generated by Django 2.2.15 on 2021-10-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditdata',
            name='TheoricalInterestRate',
            field=models.FloatField(default=0.035),
        ),
    ]
