# Generated by Django 3.1.4 on 2021-02-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='AccruedEmployeeCompensation',
            field=models.IntegerField(default=0),
        ),
    ]
