# Generated by Django 3.1.4 on 2021-02-17 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0002_cashflow_accruedemployeecompensation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflow',
            old_name='DeferredIncomeTaxExpenseBenefit',
            new_name='IncomeTaxExpenseBenefit',
        ),
    ]
