# Generated by Django 3.1.4 on 2021-02-17 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0003_auto_20210217_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflow',
            old_name='IncomeTaxExpenseBenefit',
            new_name='IncreaseDecreaseInIncomeTaxExpenseBenefit',
        ),
    ]
