# Generated by Django 2.2.15 on 2021-11-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0003_auto_20211026_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='month_end',
            field=models.IntegerField(default=0),
        ),
    ]
