# Generated by Django 3.1.4 on 2021-02-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0004_auto_20210217_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='RestructuringAndOtherSpecialCharges',
            field=models.IntegerField(default=0),
        ),
    ]
