# Generated by Django 2.2.15 on 2021-11-10 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0004_entity_month_end'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Capitalization',
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
        migrations.DeleteModel(
            name='Industry_SEC',
        ),
        migrations.DeleteModel(
            name='Intrinsic',
        ),
        migrations.DeleteModel(
            name='Master',
        ),
        migrations.DeleteModel(
            name='PeriodEndDate',
        ),
        migrations.DeleteModel(
            name='Phase',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
