# Generated by Django 3.1.4 on 2021-02-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0005_cashflow_restructuringandotherspecialcharges'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='NetChangeInShortTermBorrowings',
            field=models.IntegerField(default=0),
        ),
    ]
