# Generated by Django 2.2.15 on 2021-11-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0005_auto_20211110_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='Anomalies',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AlterField(
            model_name='entity',
            name='BridgeφFourthLastYear',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AlterField(
            model_name='entity',
            name='BridgeφLastYear',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AlterField(
            model_name='entity',
            name='BridgeφSecondLastYear',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AlterField(
            model_name='entity',
            name='BridgeφThirdLastYear',
            field=models.CharField(default=0, max_length=128),
        ),
    ]
