# Generated by Django 3.1.4 on 2021-02-19 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0007_auditdata_theoricaloperatingincomeattributabletominorityinterests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trialbalance',
            name='PropertyUnderCapitalLeaseAndFinancingObligations',
        ),
    ]
