# Generated by Django 3.1.4 on 2021-02-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0008_remove_trialbalance_propertyundercapitalleaseandfinancingobligations'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdata',
            name='NetIncomeAttributableToNonControllingInterest',
            field=models.IntegerField(default=0),
        ),
    ]
