# Generated by Django 3.1.4 on 2021-02-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0009_auditdata_netincomeattributabletononcontrollinginterest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditdata',
            old_name='TheoricalOperatingIncomeAttributableToMinorityInterests',
            new_name='TheoricalOperatingIncomeAttributableToNonControllingInterests',
        ),
    ]
