# Generated by Django 3.1.4 on 2021-02-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0010_auto_20210219_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbalance',
            name='DeferredCharges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trialbalance',
            name='DefinedBenefitPensionAndOtherSimilarPlans',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trialbalance',
            name='LongTermReceivables',
            field=models.IntegerField(default=0),
        ),
    ]
