# Generated by Django 3.1.4 on 2021-02-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0011_auto_20210221_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyTreasuryShares',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='TreasuryShares',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trialbalance',
            name='PurchaseAndSellOfTreasuryShares',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trialbalance',
            name='TreasurySharesBeginning',
            field=models.IntegerField(default=0),
        ),
    ]
