# Generated by Django 3.1.4 on 2021-02-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0012_auto_20210222_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='ClockφChange',
            field=models.FloatField(default=0),
        ),
    ]
