# Generated by Django 3.1.4 on 2021-02-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0013_entity_clockφchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='Clockφ',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entity',
            name='ClockφChange',
            field=models.IntegerField(default=0),
        ),
    ]
