# Generated by Django 3.1.4 on 2021-03-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0015_entity_stockprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='ProceedsFromStockOptionExercices',
            field=models.IntegerField(default=0),
        ),
    ]
