# Generated by Django 3.1.4 on 2021-03-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0016_cashflow_proceedsfromstockoptionexercices'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='Anomalies',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
