# Generated by Django 3.1.4 on 2021-03-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0017_entity_anomalies'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='ProceedsFromDisposalsOfBusinessesAndIntangibles',
            field=models.IntegerField(default=0),
        ),
    ]
