# Generated by Django 3.1.4 on 2021-03-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0018_cashflow_proceedsfromdisposalsofbusinessesandintangibles'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyFinancingActivitiesSEC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyInvestingActivitiesSEC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyOperatingActivitiesSEC',
            field=models.IntegerField(default=0),
        ),
    ]
