# Generated by Django 3.1.4 on 2021-03-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0019_auto_20210307_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyCurrentAssetsSEC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyCurrentLiabilitiesSEC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyNonCurrentAssetsSEC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyNonCurrentLiabilitiesSEC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyStockholdersEquitySEC',
            field=models.IntegerField(default=0),
        ),
    ]
