# Generated by Django 3.1.4 on 2021-03-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0021_cashflow_increasedecreaseoperatingleasecurrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='ReveiptOfGovernmentGrants',
            field=models.IntegerField(default=0),
        ),
    ]
