# Generated by Django 3.1.4 on 2021-03-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0022_cashflow_reveiptofgovernmentgrants'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='RepaymentsOfConvertible',
            field=models.IntegerField(default=0),
        ),
    ]
