# Generated by Django 3.1.4 on 2021-03-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0024_cashflow_issuanceofconvertible'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdata',
            name='CostOfSales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='Sales',
            field=models.IntegerField(default=0),
        ),
    ]
