# Generated by Django 3.1.4 on 2021-03-10 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0026_auditor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auditor',
        ),
    ]
