# Generated by Django 3.1.4 on 2021-03-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0027_delete_auditor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=93)),
                ('Number', models.CharField(max_length=93)),
                ('URL', models.CharField(max_length=93)),
            ],
        ),
    ]
