# Generated by Django 3.1.4 on 2021-03-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0028_auditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='Status',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
