# Generated by Django 3.1.4 on 2021-03-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0029_entity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='URL',
            field=models.CharField(default=0, max_length=66),
        ),
    ]
