# Generated by Django 3.1.4 on 2021-03-16 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0030_entity_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='URL',
            new_name='SECurl',
        ),
    ]
