# Generated by Django 3.1.4 on 2021-03-17 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0031_auto_20210316_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditor',
            name='URL',
        ),
    ]
