# Generated by Django 3.1.4 on 2021-03-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0032_remove_auditor_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdata',
            name='dad',
            field=models.CharField(default=0, max_length=13),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='IncreaseDecreaseInRetirementBenefits',
            field=models.IntegerField(default=0),
        ),
    ]
