# Generated by Django 3.1.4 on 2021-03-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0033_auto_20210318_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='IncreaseDecreaseInFairValueOfDerivativesOperating',
            field=models.IntegerField(default=0),
        ),
    ]
