# Generated by Django 3.1.4 on 2021-03-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0034_cashflow_increasedecreaseinfairvalueofderivativesoperating'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdata',
            name='IncreaseDecreaseInCash',
            field=models.IntegerField(default=0),
        ),
    ]
