# Generated by Django 3.1.4 on 2021-03-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0035_auditdata_increasedecreaseincash'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='ProceedsFromCompanyOwnedLifeInsurance',
            field=models.IntegerField(default=0),
        ),
    ]
