# Generated by Django 3.1.4 on 2021-03-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0036_cashflow_proceedsfromcompanyownedlifeinsurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='CommunityReviewed',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='entity',
            name='Status',
            field=models.CharField(default=0, max_length=7),
        ),
    ]
