# Generated by Django 3.1.4 on 2021-03-23 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0037_auto_20210323_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='CommunityReviewed',
            new_name='Reviewed',
        ),
    ]
