# Generated by Django 3.1.4 on 2021-03-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0038_auto_20210323_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='UpdateDateAndTime',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='entity',
            name='Reviewed',
            field=models.IntegerField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='entity',
            name='Update',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
