# Generated by Django 3.1.4 on 2021-04-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0039_auto_20210328_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='Reviewed',
            field=models.IntegerField(default=0),
        ),
    ]
