# Generated by Django 3.1.4 on 2021-04-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0040_auto_20210404_1034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auditor',
        ),
    ]
