# Generated by Django 3.1.4 on 2021-04-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0041_delete_auditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='phase1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='phase2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='phase3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='phase4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='phase5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='phase6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='phase7',
            field=models.IntegerField(default=0),
        ),
    ]
