# Generated by Django 3.1.4 on 2021-04-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0042_auto_20210405_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='phase51',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='phase52',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='phase53',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='phase54',
            field=models.IntegerField(default=0),
        ),
    ]
