# Generated by Django 3.1.4 on 2021-04-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0044_auto_20210405_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='phase5',
            field=models.IntegerField(default=0),
        ),
    ]
