# Generated by Django 3.1.4 on 2021-04-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0045_entity_phase5'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='phase41',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='phase42',
            field=models.IntegerField(default=0),
        ),
    ]
