# Generated by Django 3.1.4 on 2021-04-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0046_auto_20210405_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='accessionnumberseventhlastyear',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
