# Generated by Django 3.1.4 on 2021-04-06 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0047_entity_accessionnumberseventhlastyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='phase4',
        ),
    ]
