# Generated by Django 3.1.4 on 2021-04-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0048_remove_entity_phase4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditdata',
            name='Period',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='Period',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='eighthlastyear',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='fifthlastyear',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='fourthlastquarter',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='fourthlastyear',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='lastquarter',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='lastyear',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='secondlastquarter',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='secondlastyear',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='seventhlastyear',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='sixthlastyear',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='thirdlastquarter',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='thirdlastyear',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='trialbalance',
            name='Period',
            field=models.DateField(null=True),
        ),
    ]
