# Generated by Django 3.1.4 on 2021-04-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0049_auto_20210407_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditdata',
            name='Period',
            field=models.CharField(default=0, max_length=13),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='Period',
            field=models.CharField(default=0, max_length=13),
        ),
        migrations.AlterField(
            model_name='entity',
            name='eighthlastyear',
            field=models.CharField(default=0, max_length=13),
        ),
        migrations.AlterField(
            model_name='entity',
            name='fifthlastyear',
            field=models.CharField(default=0, max_length=13),
        ),
        migrations.AlterField(
            model_name='entity',
            name='fourthlastquarter',
            field=models.CharField(default=0, max_length=13),
        ),
        migrations.AlterField(
            model_name='entity',
            name='fourthlastyear',
            field=models.CharField(default=0, max_length=13),
        ),
        migrations.AlterField(
            model_name='entity',
            name='lastquarter',
            field=models.CharField(default=0, max_length=13),
        ),
        migrations.AlterField(
            model_name='entity',
            name='lastyear',
            field=models.CharField(default=0, max_length=13),
        ),
        migrations.AlterField(
            model_name='entity',
            name='secondlastquarter',
            field=models.CharField(default=0, max_length=13),
        ),
        migrations.AlterField(
            model_name='entity',
            name='secondlastyear',
            field=models.CharField(default=0, max_length=13),
        ),
        migrations.AlterField(
            model_name='entity',
            name='seventhlastyear',
            field=models.CharField(default=0, max_length=13),
        ),
        migrations.AlterField(
            model_name='entity',
            name='sixthlastyear',
            field=models.CharField(default=0, max_length=13),
        ),
        migrations.AlterField(
            model_name='entity',
            name='thirdlastquarter',
            field=models.CharField(default=0, max_length=13),
        ),
        migrations.AlterField(
            model_name='entity',
            name='thirdlastyear',
            field=models.CharField(default=0, max_length=13),
        ),
        migrations.AlterField(
            model_name='trialbalance',
            name='Period',
            field=models.CharField(default=0, max_length=13),
        ),
    ]
