# Generated by Django 3.1.4 on 2021-04-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0050_auto_20210407_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='test',
            field=models.DateTimeField(null=True),
        ),
    ]
