# Generated by Django 3.1.4 on 2021-04-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0051_entity_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditdata',
            name='dad',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='eighthlastyear',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='test',
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='Period',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='Period',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='fifthlastyear',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='fourthlastyear',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='lastyear',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='secondlastyear',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='seventhlastyear',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='sixthlastyear',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='thirdlastyear',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='trialbalance',
            name='Period',
            field=models.DateField(null=True),
        ),
    ]
