# Generated by Django 3.1.4 on 2021-04-07 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0052_auto_20210407_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='fourthlastquarter',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='lastquarter',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='secondlastquarter',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='thirdlastquarter',
        ),
    ]
