# Generated by Django 3.1.4 on 2021-04-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0054_auto_20210407_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='UpdateDateAndTime',
            field=models.DateTimeField(null=True),
        ),
    ]
