# Generated by Django 3.1.4 on 2021-04-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0055_auto_20210407_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase1', models.IntegerField(default=0)),
                ('phase2', models.IntegerField(default=0)),
                ('phase3', models.IntegerField(default=0)),
                ('phase41', models.IntegerField(default=0)),
                ('phase42', models.IntegerField(default=0)),
                ('phase43', models.IntegerField(default=0)),
                ('phase5', models.IntegerField(default=0)),
                ('phase61', models.IntegerField(default=0)),
                ('phase62', models.IntegerField(default=0)),
                ('phase63', models.IntegerField(default=0)),
                ('phase64', models.IntegerField(default=0)),
                ('phase7', models.IntegerField(default=0)),
                ('phase8', models.IntegerField(default=0)),
                ('prepared', models.IntegerField(default=0)),
                ('audited', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='audited',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='prepared',
            field=models.IntegerField(default=0),
        ),
    ]
