# Generated by Django 3.1.4 on 2021-04-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0056_auto_20210408_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='phase4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='database',
            name='phase6',
            field=models.IntegerField(default=0),
        ),
    ]
