# Generated by Django 3.1.4 on 2021-04-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0057_auto_20210408_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='amendfifthlastyear',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='entity',
            name='amendfourthlastyear',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='entity',
            name='amendlastyear',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='entity',
            name='amendsecondlastyear',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='entity',
            name='amendseventhlastyear',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='entity',
            name='amendsixthlastyear',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='entity',
            name='amendthirdlastyear',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
