# Generated by Django 3.1.4 on 2021-04-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0058_auto_20210408_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='accessionnumberfifthlastyear',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='entity',
            name='accessionnumberfourthlastyear',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='entity',
            name='accessionnumberlastyear',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='entity',
            name='accessionnumbersecondlastyear',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='entity',
            name='accessionnumberseventhlastyear',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='entity',
            name='accessionnumbersixthlastyear',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='entity',
            name='accessionnumberthirdlastyear',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='entity',
            name='amendfifthlastyear',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='entity',
            name='amendfourthlastyear',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='entity',
            name='amendlastyear',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='entity',
            name='amendsecondlastyear',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='entity',
            name='amendseventhlastyear',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='entity',
            name='amendsixthlastyear',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='entity',
            name='amendthirdlastyear',
            field=models.CharField(default='', max_length=5),
        ),
    ]
