# Generated by Django 3.1.4 on 2021-04-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0059_auto_20210409_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='urlbalancesheetfifthlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlbalancesheetfourthlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlbalancesheetlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlbalancesheetsecondlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlbalancesheetseventhlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlbalancesheetsixthlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlbalancesheetthirdlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlcashflowfifthlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlcashflowfourthlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlcashflowlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlcashflowsecondlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlcashflowseventhlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlcashflowsixthlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlcashflowthirdlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlcomprehensiveincomefifthlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlcomprehensiveincomefourthlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlcomprehensiveincomelastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlcomprehensiveincomesecondlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlcomprehensiveincomeseventhlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlcomprehensiveincomesixthlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlcomprehensiveincomethirdlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlincomestatementfifthlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlincomestatementfourthlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlincomestatementlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlincomestatementsecondlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlincomestatementseventhlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlincomestatementsixthlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlincomestatementthirdlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlstockholdersequityfifthlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlstockholdersequityfourthlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlstockholdersequitylastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlstockholdersequitysecondlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlstockholdersequityseventhlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlstockholdersequitysixthlastyear',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='entity',
            name='urlstockholdersequitythirdlastyear',
            field=models.CharField(default='', max_length=170),
        ),
    ]
