# Generated by Django 3.1.4 on 2021-04-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0060_auto_20210409_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='phase65',
            field=models.IntegerField(default=0),
        ),
    ]
