# Generated by Django 3.1.4 on 2021-04-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0061_database_phase65'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
