# Generated by Django 3.1.4 on 2021-04-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0064_auto_20210410_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='phase71',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='database',
            name='phase72',
            field=models.IntegerField(default=0),
        ),
    ]
