# Generated by Django 3.1.4 on 2021-04-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0065_auto_20210417_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdata',
            name='AccessionNumber',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='AccessionNumber',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='trialbalance',
            name='AccessionNumber',
            field=models.CharField(default='', max_length=20),
        ),
    ]
