# Generated by Django 3.1.4 on 2021-04-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0066_auto_20210417_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdata',
            name='PeriodEndDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='PeriodEndDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='trialbalance',
            name='PeriodEndDate',
            field=models.DateField(null=True),
        ),
    ]
