# Generated by Django 3.1.4 on 2021-04-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0067_auto_20210417_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='phase73',
            field=models.IntegerField(default=0),
        ),
    ]
