# Generated by Django 3.1.4 on 2021-04-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0068_database_phase73'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='AnomaliesRatio',
            field=models.FloatField(default=0),
        ),
    ]
