# Generated by Django 3.1.4 on 2021-04-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0069_entity_anomaliesratio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='phase73',
        ),
        migrations.AlterField(
            model_name='entity',
            name='AnomaliesRatio',
            field=models.IntegerField(default=999999),
        ),
    ]
