# Generated by Django 3.1.4 on 2021-04-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0070_auto_20210417_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='phase73',
            field=models.IntegerField(default=0),
        ),
    ]
