# Generated by Django 3.1.4 on 2021-04-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0071_database_phase73'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='phase74',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='database',
            name='phase75',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='database',
            name='phase76',
            field=models.IntegerField(default=0),
        ),
    ]
