# Generated by Django 3.1.4 on 2021-04-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0072_auto_20210418_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='phase77',
            field=models.IntegerField(default=0),
        ),
    ]
