# Generated by Django 3.1.4 on 2021-04-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0074_auto_20210419_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='MarketCapitalization',
            field=models.IntegerField(default=0),
        ),
    ]
