# Generated by Django 3.1.4 on 2021-04-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0075_entity_marketcapitalization'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdata',
            name='Status',
            field=models.CharField(default=0, max_length=7),
        ),
    ]
