# Generated by Django 3.1.4 on 2021-04-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0076_auditdata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditdata',
            name='Status',
            field=models.CharField(default='', max_length=7),
        ),
    ]
