# Generated by Django 3.1.4 on 2021-04-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0077_auto_20210420_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbalance',
            name='WorkInProgress',
            field=models.IntegerField(default=0),
        ),
    ]
