# Generated by Django 3.1.4 on 2021-04-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0078_trialbalance_workinprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='phase78',
            field=models.IntegerField(default=0),
        ),
    ]
