# Generated by Django 3.1.4 on 2021-04-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0083_auto_20210421_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='AnomaliesRatio1',
            field=models.IntegerField(default=9999),
        ),
        migrations.AlterField(
            model_name='entity',
            name='AnomaliesRatio2',
            field=models.IntegerField(default=9999),
        ),
        migrations.AlterField(
            model_name='entity',
            name='AnomaliesRatio3',
            field=models.IntegerField(default=9999),
        ),
        migrations.AlterField(
            model_name='entity',
            name='AnomaliesRatio4',
            field=models.IntegerField(default=9999),
        ),
        migrations.AlterField(
            model_name='entity',
            name='AnomaliesRatio5',
            field=models.IntegerField(default=9999),
        ),
        migrations.AlterField(
            model_name='entity',
            name='AnomaliesRatio6',
            field=models.IntegerField(default=9999),
        ),
    ]
