# Generated by Django 3.1.4 on 2021-04-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0086_database_onboarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='StockPriceUpdate',
            field=models.DateTimeField(null=True),
        ),
    ]
