# Generated by Django 3.1.4 on 2021-05-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0087_entity_stockpriceupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflow',
            name='PaymentsForTaxesRelatedToNetShareSettlementOfEquityAward',
        ),
        migrations.AddField(
            model_name='cashflow',
            name='PaymentOfDeferredContingentConsideration',
            field=models.IntegerField(default=0),
        ),
    ]
