# Generated by Django 3.1.4 on 2021-05-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0088_auto_20210501_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='FinancingCosts',
            field=models.IntegerField(default=0),
        ),
    ]
