# Generated by Django 3.1.4 on 2021-05-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0089_cashflow_financingcosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbalance',
            name='EquityMethodInvesteesIncome',
            field=models.IntegerField(default=0),
        ),
    ]
