# Generated by Django 3.1.4 on 2021-05-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0090_trialbalance_equitymethodinvesteesincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='PaymentOfLicenseFee',
            field=models.IntegerField(default=0),
        ),
    ]
