# Generated by Django 3.1.4 on 2021-05-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0091_cashflow_paymentoflicensefee'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='LoanRepaymentFromEquityInvestee',
            field=models.IntegerField(default=0),
        ),
    ]
