# Generated by Django 3.1.4 on 2021-05-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0093_auto_20210503_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbalance',
            name='RightOfUseAssetsCurrent',
            field=models.IntegerField(default=0),
        ),
    ]
