# Generated by Django 3.1.4 on 2021-05-03 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0094_trialbalance_rightofuseassetscurrent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflow',
            old_name='PaymentOfDeferredContingentConsideration',
            new_name='IncreaseDecreaseDeferredContingentConsideration',
        ),
    ]
