# Generated by Django 3.1.4 on 2021-05-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0095_auto_20210503_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflow',
            old_name='ProceedsFromCompanyOwnedLifeInsurance',
            new_name='ProceedsRelatedToInsuranceSettlement',
        ),
    ]
