# Generated by Django 3.1.4 on 2021-05-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0096_auto_20210504_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbalance',
            name='ContingentConsideration',
            field=models.IntegerField(default=0),
        ),
    ]
