# Generated by Django 3.1.4 on 2021-05-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0097_trialbalance_contingentconsideration'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbalance',
            name='PreferredSharesLiability',
            field=models.IntegerField(default=0),
        ),
    ]
