# Generated by Django 3.1.4 on 2021-05-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0098_trialbalance_preferredsharesliability'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='NetChangeInNonControllingInterests',
            field=models.IntegerField(default=0),
        ),
    ]
