# Generated by Django 3.1.4 on 2021-05-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0099_cashflow_netchangeinnoncontrollinginterests'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbalance',
            name='PrepaidTaxAssetsCurrent',
            field=models.IntegerField(default=0),
        ),
    ]
