# Generated by Django 3.1.4 on 2021-05-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0100_trialbalance_prepaidtaxassetscurrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='IncreaseDecreaseFinanceLeaseCurrent',
            field=models.IntegerField(default=0),
        ),
    ]
