# Generated by Django 3.1.4 on 2021-05-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0101_cashflow_increasedecreasefinanceleasecurrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbalance',
            name='RedeemableNonControllingInterest',
            field=models.IntegerField(default=0),
        ),
    ]
