# Generated by Django 3.1.4 on 2021-05-05 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0102_trialbalance_redeemablenoncontrollinginterest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trialbalance',
            old_name='RedeemableNonControllingInterest',
            new_name='RedeemableNonControllingInterests',
        ),
    ]
