# Generated by Django 3.1.4 on 2021-05-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0103_auto_20210505_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbalance',
            name='RefundableTaxAssetsNonCurrent',
            field=models.IntegerField(default=0),
        ),
    ]
