# Generated by Django 3.1.4 on 2021-05-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0104_trialbalance_refundabletaxassetsnoncurrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyConvertibleDebt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='ConvertibleDebt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trialbalance',
            name='ConvertibleDebtBeginning',
            field=models.IntegerField(default=0),
        ),
    ]
