# Generated by Django 3.1.4 on 2021-05-09 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0105_auto_20210509_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='EntityIncorporationStateCountryCode',
            new_name='IndustryCode',
        ),
    ]
