# Generated by Django 3.1.4 on 2021-05-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0106_auto_20210509_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='RegionCode',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='entity',
            name='IndustryCode',
            field=models.CharField(default='', max_length=10),
        ),
    ]
