# Generated by Django 3.1.4 on 2021-05-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0107_auto_20210509_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='NetChangeForwardAndHedgesClassifiedAsFinancingActivities',
            field=models.IntegerField(default=0),
        ),
    ]
