# Generated by Django 3.1.4 on 2021-05-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0108_cashflow_netchangeforwardandhedgesclassifiedasfinancingactivities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflow',
            old_name='NetChangeForwardAndHedgesClassifiedAsFinancingActivities',
            new_name='NetChangeInForwardAndHedgesClassifiedAsFinancingActivities',
        ),
    ]
