# Generated by Django 3.1.4 on 2021-05-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0109_auto_20210510_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trialbalance',
            name='CapitalLeaseAndFinancingObligationsCurrent',
        ),
        migrations.RemoveField(
            model_name='trialbalance',
            name='CapitalLeaseAndFinancingObligationsNonCurrent',
        ),
        migrations.AddField(
            model_name='trialbalance',
            name='LeaseIncentiveObligation',
            field=models.IntegerField(default=0),
        ),
    ]
