# Generated by Django 3.1.4 on 2021-05-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0110_auto_20210510_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbalance',
            name='AcquisitionOfNonControllingInterests',
            field=models.IntegerField(default=0),
        ),
    ]
