# Generated by Django 3.1.4 on 2021-05-11 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0113_auto_20210510_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trialbalance',
            old_name='impairmentRestructuringAndOtherSpecialCharges',
            new_name='ImpairmentRestructuringAndOtherSpecialCharges',
        ),
    ]
