# Generated by Django 3.1.4 on 2021-05-11 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0114_auto_20210510_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trialbalance',
            old_name='inventories',
            new_name='Inventories',
        ),
    ]
