# Generated by Django 3.1.4 on 2021-05-11 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0115_auto_20210510_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditdata',
            old_name='incomeBeforeTaxes',
            new_name='IncomeBeforeTaxes',
        ),
        migrations.RenameField(
            model_name='trialbalance',
            old_name='investments',
            new_name='Investments',
        ),
    ]
