# Generated by Django 3.1.4 on 2021-05-11 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0116_auto_20210510_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trialbalance',
            old_name='intangibleAssets',
            new_name='IntangibleAssets',
        ),
    ]
