# Generated by Django 3.1.4 on 2021-05-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0118_auto_20210510_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='CapitalizationCode',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
