# Generated by Django 3.1.4 on 2021-05-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0119_entity_capitalizationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='IntrinsicValueCode',
            field=models.CharField(default='', max_length=10),
        ),
    ]
