# Generated by Django 3.1.4 on 2021-05-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0120_entity_intrinsicvaluecode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='ClockφChange',
        ),
        migrations.AddField(
            model_name='entity',
            name='IntrinsicValue',
            field=models.IntegerField(default=0),
        ),
    ]
