# Generated by Django 3.1.4 on 2021-05-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0121_auto_20210511_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditdata',
            old_name='EntityCommonStockSharesOutstanding',
            new_name='CommonStockSharesOutstanding',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='EntityCommonStockSharesOutstanding',
            new_name='CommonStockSharesOutstanding',
        ),
        migrations.AddField(
            model_name='auditdata',
            name='StockPriceUpdate',
            field=models.FloatField(default=0),
        ),
    ]
