# Generated by Django 3.1.4 on 2021-05-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0122_auto_20210511_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditdata',
            old_name='CommonStockSharesOutstanding',
            new_name='CommonSharesOutstanding',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='CommonStockSharesOutstanding',
            new_name='CommonSharesOutstanding',
        ),
    ]
