# Generated by Django 3.1.4 on 2021-05-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0123_auto_20210511_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdata',
            name='URLoustandingshares',
            field=models.CharField(default='', max_length=100),
        ),
    ]
