# Generated by Django 3.1.4 on 2021-05-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0124_auditdata_urloustandingshares'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Capitalization', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Industry', models.CharField(max_length=61)),
                ('IndustryCode', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IntrinsicValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IntrinsicValue', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=93)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.CharField(max_length=44)),
                ('RegionCode', models.CharField(default='', max_length=4)),
            ],
        ),
    ]
