# Generated by Django 3.1.4 on 2021-05-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0126_auto_20210512_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalization',
            name='Len',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='industry',
            name='Len',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intrinsicvalue',
            name='Len',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phase',
            name='Description',
            field=models.CharField(default='', max_length=93),
        ),
        migrations.AddField(
            model_name='phase',
            name='Len',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='Description',
            field=models.CharField(default='', max_length=93),
        ),
        migrations.AddField(
            model_name='region',
            name='Len',
            field=models.IntegerField(default=0),
        ),
    ]
