# Generated by Django 3.1.4 on 2021-05-12 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0127_auto_20210512_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phase',
            old_name='Name',
            new_name='url',
        ),
    ]
