# Generated by Django 3.1.4 on 2021-05-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0128_auto_20210512_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='Name',
            field=models.CharField(default='', max_length=93),
        ),
        migrations.AlterField(
            model_name='phase',
            name='url',
            field=models.CharField(max_length=10),
        ),
    ]
