# Generated by Django 3.1.4 on 2021-05-13 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0130_phase_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phase',
            old_name='Rank',
            new_name='Status',
        ),
    ]
