# Generated by Django 3.1.4 on 2021-05-13 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0131_auto_20210512_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='url',
        ),
    ]
