# Generated by Django 3.1.4 on 2021-05-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0132_auto_20210512_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industry',
            old_name='Industry',
            new_name='Description',
        ),
        migrations.AddField(
            model_name='industry',
            name='Status',
            field=models.IntegerField(default=0),
        ),
    ]
