# Generated by Django 3.1.4 on 2021-05-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0134_auto_20210512_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='Description',
            field=models.CharField(max_length=93),
        ),
    ]
