# Generated by Django 3.1.4 on 2021-05-13 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0135_auto_20210512_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capitalization',
            old_name='Capitalization',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='intrinsicvalue',
            old_name='IntrinsicValue',
            new_name='Description',
        ),
    ]
