# Generated by Django 3.1.4 on 2021-05-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0136_auto_20210512_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='Code',
            field=models.CharField(default='', max_length=9),
        ),
    ]
