# Generated by Django 3.1.4 on 2021-05-13 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0137_industry_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Database',
        ),
    ]
