# Generated by Django 3.1.4 on 2021-05-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0139_entity_region_db'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='Status',
            new_name='db',
        ),
        migrations.AddField(
            model_name='entity',
            name='Industry_db',
            field=models.IntegerField(default=0),
        ),
    ]
