# Generated by Django 3.1.4 on 2021-05-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0140_auto_20210512_2252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IntrinsicValue',
            new_name='Intrinsic',
        ),
        migrations.AddField(
            model_name='entity',
            name='Capitalization_db',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='Intrinsic_db',
            field=models.IntegerField(default=0),
        ),
    ]
