# Generated by Django 3.1.4 on 2021-05-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0143_auto_20210513_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccumulatedOtherComprehensiveIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AccumulatedOtherComprehensiveIncomeAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AccumulatedOtherComprehensiveIncomeBeginningBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AccumulatedOtherComprehensiveIncomeBeginningBalanceAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Administrative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AdministrativeAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CommonShares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CommonSharesAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CommonSharesBeginningBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CommonSharesBeginningBalanceAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ComprehensiveIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ComprehensiveIncomeAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CostOfSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CostOfSalesAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentAssetAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentLiability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentLiabilityAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NonCurrentAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NonCurrentAssetAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NonCurrentLiability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NonCurrentLiabilityAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NonOperating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NonOperatingAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OtherEquityComponents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OtherEquityComponentsAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OtherEquityComponentsBeginningBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OtherEquityComponentsBeginningBalanceAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OtherNonOperatingExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OtherNonOperatingExpensesAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OtherOperatingExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OtherOperatingExpensesAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchAndDevelopment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchAndDevelopmentAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Restructuring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RestructuringAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RetainedEarnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RetainedEarningsAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RetainedEarningsBeginningBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RetainedEarningsBeginningBalanceAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TaxAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
    ]
