# Generated by Django 3.1.4 on 2021-05-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0144_accumulatedothercomprehensiveincome_accumulatedothercomprehensiveincomeaudit_accumulatedothercompreh'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradingSymbol', models.CharField(max_length=7, unique=True)),
                ('PeriodEndDate', models.DateField(unique=True)),
                ('Description', models.CharField(max_length=99, unique=True)),
                ('ref', models.CharField(max_length=99, unique=True)),
                ('Value', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='CurrentAsset',
            new_name='CurrentAssets',
        ),
        migrations.RenameModel(
            old_name='CurrentAssetAudit',
            new_name='CurrentAssetsAudit',
        ),
        migrations.RenameModel(
            old_name='CurrentLiability',
            new_name='CurrentLiabilities',
        ),
        migrations.RenameModel(
            old_name='NonCurrentAsset',
            new_name='CurrentLiabilitiesAudit',
        ),
        migrations.RenameModel(
            old_name='NonCurrentAssetAudit',
            new_name='NonCurrentAssets',
        ),
        migrations.RenameModel(
            old_name='CurrentLiabilityAudit',
            new_name='NonCurrentAssetsAudit',
        ),
        migrations.RenameModel(
            old_name='NonCurrentLiabilityAudit',
            new_name='NonCurrentLiabilities',
        ),
        migrations.RenameModel(
            old_name='NonCurrentLiability',
            new_name='NonCurrentLiabilitiesAudit',
        ),
    ]
