# Generated by Django 3.1.4 on 2021-05-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0146_auto_20210513_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareBasedCompensationCF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
