# Generated by Django 3.1.4 on 2021-05-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0149_auto_20210513_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entities', models.IntegerField(default=0)),
            ],
        ),
    ]
