# Generated by Django 3.1.4 on 2021-05-13 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0151_auto_20210513_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='phases',
            new_name='audited',
        ),
    ]
