# Generated by Django 3.1.4 on 2021-05-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0152_auto_20210513_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='eq',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='master',
            name='onboarded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='master',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
