# Generated by Django 3.1.4 on 2021-05-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0154_auto_20210513_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalization',
            name='leader',
            field=models.CharField(default='', max_length=93),
        ),
    ]
