# Generated by Django 3.1.4 on 2021-05-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0155_capitalization_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodEndDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.DateField(null=True)),
                ('dbp', models.DateField(null=True)),
                ('Len', models.IntegerField(default=0)),
            ],
        ),
    ]
