# Generated by Django 3.1.4 on 2021-05-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0156_periodenddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='PeriodEndDate',
            field=models.DateField(null=True),
        ),
    ]
