# Generated by Django 3.1.4 on 2021-05-15 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0157_entity_periodenddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='PeriodEndDate',
            new_name='PeriodEndDate_db',
        ),
    ]
