# Generated by Django 3.1.4 on 2021-05-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0159_auto_20210514_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='URL',
            field=models.CharField(default='', max_length=99),
        ),
    ]
