# Generated by Django 3.1.4 on 2021-05-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0161_auto_20210515_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='CommonShareIntrinsicValueFourthLastYear',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='CommonShareIntrinsicValueLastYear',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='CommonShareIntrinsicValueSecondLastYear',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='CommonShareIntrinsicValueThirdLastYear',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='CommonSharesIntrinsicValueFourthLastYear',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='CommonSharesIntrinsicValueLastYear',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='CommonSharesIntrinsicValueSecondLastYear',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='CommonSharesIntrinsicValueThirdLastYear',
            field=models.IntegerField(default=0),
        ),
    ]
