# Generated by Django 3.1.4 on 2021-05-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0163_auto_20210515_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='MarketCapitalization',
            new_name='MarketCapitalizationLastYear',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='SharePrice',
            new_name='SharePriceLastYear',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='SharePriceUpdate',
        ),
        migrations.AddField(
            model_name='entity',
            name='CommonSharesOutstandingFourthLastYear',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='CommonSharesOutstandingSecondLastYear',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='CommonSharesOutstandingThirdLastYear',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entity',
            name='Update',
            field=models.DateTimeField(null=True),
        ),
    ]
