# Generated by Django 3.1.4 on 2021-05-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0164_auto_20210515_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='MarketCapitalizationFourthLastYear',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='MarketCapitalizationSecondLastYear',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='MarketCapitalizationThirdLastYear',
            field=models.IntegerField(default=0),
        ),
    ]
