# Generated by Django 3.1.4 on 2021-05-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0165_auto_20210515_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='SharePriceFourthLastYear',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='SharePriceSecondLastYear',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='SharePriceThirdLastYear',
            field=models.FloatField(default=0),
        ),
    ]
