# Generated by Django 3.1.4 on 2021-05-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0166_auto_20210515_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='UpdateDateAndTime',
            new_name='SEC_UpdateDateAndTime',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='Update',
            new_name='SecuritiesUpdate',
        ),
        migrations.AddField(
            model_name='entity',
            name='SEC_Update',
            field=models.DateField(null=True),
        ),
    ]
