# Generated by Django 3.1.4 on 2021-05-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0167_auto_20210515_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='Bridgeφ',
            new_name='BridgeφLastYear',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='Clockφ',
            new_name='ClockφLastYear',
        ),
        migrations.AddField(
            model_name='entity',
            name='BridgeφFourthLastYear',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='entity',
            name='BridgeφSecondLastYear',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='entity',
            name='BridgeφThirdLastYear',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='entity',
            name='ClockφFourthLastYear',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='ClockφSecondLastYear',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='ClockφThirdLastYear',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='OpinionFourthLastYear',
            field=models.CharField(default='', max_length=55),
        ),
        migrations.AddField(
            model_name='entity',
            name='OpinionLastYear',
            field=models.CharField(default='', max_length=55),
        ),
        migrations.AddField(
            model_name='entity',
            name='OpinionSecondLastYear',
            field=models.CharField(default='', max_length=55),
        ),
        migrations.AddField(
            model_name='entity',
            name='OpinionThirdLastYear',
            field=models.CharField(default='', max_length=55),
        ),
    ]
