# Generated by Django 3.1.4 on 2021-05-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0168_auto_20210515_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='OpinionFourthLastYear',
            new_name='OpinionφFourthLastYear',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='OpinionLastYear',
            new_name='OpinionφLastYear',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='OpinionSecondLastYear',
            new_name='OpinionφSecondLastYear',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='OpinionThirdLastYear',
            new_name='OpinionφThirdLastYear',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='CapitalizationCode',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='CurrentFiscalYearEndDate',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='IntrinsicValue',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='IntrinsicValueCode',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='Regulator',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='Reviewed',
        ),
    ]
