# Generated by Django 3.1.4 on 2021-05-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0170_auto_20210515_1314'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SharePrice',
            new_name='CommonSharePrice',
        ),
        migrations.RenameField(
            model_name='auditdata',
            old_name='SharePrice',
            new_name='CommonSharePrice',
        ),
        migrations.RenameField(
            model_name='auditdata',
            old_name='SharePriceUpdate',
            new_name='CommonSharePriceUpdate',
        ),
    ]
