# Generated by Django 3.1.4 on 2021-05-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0171_auto_20210515_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.IntegerField(default=0)),
                ('Description', models.CharField(max_length=44)),
                ('Len', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='auditdata',
            name='Status',
        ),
    ]
