# Generated by Django 3.1.4 on 2021-05-17 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0172_auto_20210517_0858'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sectors',
            new_name='Sector',
        ),
    ]
