# Generated by Django 3.1.4 on 2021-05-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0173_auto_20210517_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.IntegerField(default=0)),
                ('sector_db', models.IntegerField(default=0)),
                ('Description', models.CharField(max_length=61)),
                ('Len', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Aerospace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.IntegerField(default=0)),
                ('sector_db', models.IntegerField(default=0)),
                ('Description', models.CharField(max_length=61)),
                ('Len', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AgricultureForestry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.IntegerField(default=0)),
                ('sector_db', models.IntegerField(default=0)),
                ('Description', models.CharField(max_length=61)),
                ('Len', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Automobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.IntegerField(default=0)),
                ('sector_db', models.IntegerField(default=0)),
                ('Description', models.CharField(max_length=61)),
                ('Len', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Banking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.IntegerField(default=0)),
                ('sector_db', models.IntegerField(default=0)),
                ('Description', models.CharField(max_length=61)),
                ('Len', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BreweriesBottlers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.IntegerField(default=0)),
                ('sector_db', models.IntegerField(default=0)),
                ('Description', models.CharField(max_length=61)),
                ('Len', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChemicalEngineering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.IntegerField(default=0)),
                ('sector_db', models.IntegerField(default=0)),
                ('Description', models.CharField(max_length=61)),
                ('Len', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.IntegerField(default=0)),
                ('sector_db', models.IntegerField(default=0)),
                ('Description', models.CharField(max_length=61)),
                ('Len', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.IntegerField(default=0)),
                ('sector_db', models.IntegerField(default=0)),
                ('Description', models.CharField(max_length=61)),
                ('Len', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.IntegerField(default=0)),
                ('sector_db', models.IntegerField(default=0)),
                ('Description', models.CharField(max_length=61)),
                ('Len', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyUtilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.IntegerField(default=0)),
                ('sector_db', models.IntegerField(default=0)),
                ('Description', models.CharField(max_length=61)),
                ('Len', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.IntegerField(default=0)),
                ('sector_db', models.IntegerField(default=0)),
                ('Description', models.CharField(max_length=61)),
                ('Len', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FishingHunting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.IntegerField(default=0)),
                ('sector_db', models.IntegerField(default=0)),
                ('Description', models.CharField(max_length=61)),
                ('Len', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Government',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.IntegerField(default=0)),
                ('sector_db', models.IntegerField(default=0)),
                ('Description', models.CharField(max_length=61)),
                ('Len', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HealthCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.IntegerField(default=0)),
                ('sector_db', models.IntegerField(default=0)),
                ('Description', models.CharField(max_length=61)),
                ('Len', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InformationTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.IntegerField(default=0)),
                ('sector_db', models.IntegerField(default=0)),
                ('Description', models.CharField(max_length=61)),
                ('Len', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.IntegerField(default=0)),
                ('sector_db', models.IntegerField(default=0)),
                ('Description', models.CharField(max_length=61)),
                ('Len', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.IntegerField(default=0)),
                ('sector_db', models.IntegerField(default=0)),
                ('Description', models.CharField(max_length=61)),
                ('Len', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MiningQuarrying',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.IntegerField(default=0)),
                ('sector_db', models.IntegerField(default=0)),
                ('Description', models.CharField(max_length=61)),
                ('Len', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.IntegerField(default=0)),
                ('sector_db', models.IntegerField(default=0)),
                ('Description', models.CharField(max_length=61)),
                ('Len', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Telecom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.IntegerField(default=0)),
                ('sector_db', models.IntegerField(default=0)),
                ('Description', models.CharField(max_length=61)),
                ('Len', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.IntegerField(default=0)),
                ('sector_db', models.IntegerField(default=0)),
                ('Description', models.CharField(max_length=61)),
                ('Len', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.IntegerField(default=0)),
                ('sector_db', models.IntegerField(default=0)),
                ('Description', models.CharField(max_length=61)),
                ('Len', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Industry',
            new_name='Industry_SEC',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='Industry',
            new_name='Industry_SEC',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='IndustryCode',
            new_name='Industry_SECCode',
        ),
        migrations.RenameField(
            model_name='entity',
            old_name='Industry_db',
            new_name='Industry_SEC_db',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='Len',
        ),
        migrations.AddField(
            model_name='entity',
            name='Sector_db',
            field=models.IntegerField(default=0),
        ),
    ]
