# Generated by Django 3.1.4 on 2021-05-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0175_auto_20210517_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.IntegerField(default=0)),
                ('sector_db', models.IntegerField(default=0)),
                ('Description', models.CharField(max_length=61)),
                ('Len', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Advertising',
        ),
        migrations.DeleteModel(
            name='Aerospace',
        ),
        migrations.DeleteModel(
            name='AgricultureForestry',
        ),
        migrations.DeleteModel(
            name='Automobile',
        ),
        migrations.DeleteModel(
            name='Banking',
        ),
        migrations.DeleteModel(
            name='BreweriesBottlers',
        ),
        migrations.DeleteModel(
            name='ChemicalEngineering',
        ),
        migrations.DeleteModel(
            name='Construction',
        ),
        migrations.DeleteModel(
            name='Culture',
        ),
        migrations.DeleteModel(
            name='Distribution',
        ),
        migrations.DeleteModel(
            name='EnergyUtilities',
        ),
        migrations.DeleteModel(
            name='Finance',
        ),
        migrations.DeleteModel(
            name='FishingHunting',
        ),
        migrations.DeleteModel(
            name='Government',
        ),
        migrations.DeleteModel(
            name='HealthCare',
        ),
        migrations.DeleteModel(
            name='InformationTechnology',
        ),
        migrations.DeleteModel(
            name='Insurance',
        ),
        migrations.DeleteModel(
            name='Legal',
        ),
        migrations.DeleteModel(
            name='MiningQuarrying',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
        migrations.DeleteModel(
            name='Telecom',
        ),
        migrations.DeleteModel(
            name='Transportation',
        ),
        migrations.DeleteModel(
            name='Universities',
        ),
    ]
