# Generated by Django 3.1.4 on 2021-05-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0176_auto_20210517_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industry',
            old_name='sector_db',
            new_name='Sector_db',
        ),
        migrations.RenameField(
            model_name='trialbalance',
            old_name='CommonShareIssued',
            new_name='CommonSharesIssued',
        ),
        migrations.AlterField(
            model_name='capitalization',
            name='db',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='db',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='intrinsic',
            name='db',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='periodenddate',
            name='db',
            field=models.DateField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='db',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='db',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='db',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
