# Generated by Django 3.1.4 on 2021-05-20 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0177_auto_20210520_1511'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommonShareRepurchasedAndRetired',
            new_name='CommonSharesRepurchasedAndRetired',
        ),
        migrations.RenameModel(
            old_name='ProceedsFromIssuanceOfCommonShare',
            new_name='ProceedsFromIssuanceOfCommonShares',
        ),
        migrations.RenameModel(
            old_name='ProceedsFromShareOptionExercices',
            new_name='ProceedsFromSharePurchasePlanAndOptionsExercice',
        ),
        migrations.RenameField(
            model_name='cashflow',
            old_name='ProceedsFromIssuanceOfCommonShare',
            new_name='ProceedsFromIssuanceOfCommonShares',
        ),
        migrations.RenameField(
            model_name='cashflow',
            old_name='ProceedsFromShareOptionExercices',
            new_name='ProceedsFromSharePurchasePlanAndOptionsExercice',
        ),
        migrations.RenameField(
            model_name='trialbalance',
            old_name='CommonShareRepurchasedAndRetired',
            new_name='CommonSharesRepurchasedAndRetired',
        ),
    ]
