# Generated by Django 3.1.4 on 2021-05-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0178_auto_20210520_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdata',
            name='db',
            field=models.IntegerField(default=0),
        ),
    ]
