# Generated by Django 3.1.4 on 2021-05-20 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0179_auditdata_db'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentsForRepurchaseOfCommonShare',
            new_name='PaymentsForRepurchaseOfCommonShares',
        ),
        migrations.RenameField(
            model_name='cashflow',
            old_name='PaymentsForRepurchaseOfCommonShare',
            new_name='PaymentsForRepurchaseOfCommonShares',
        ),
    ]
