# Generated by Django 3.1.4 on 2021-05-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0180_auto_20210520_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
