# Generated by Django 3.1.4 on 2021-05-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0181_auto_20210523_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='ClockφFourthLastYear',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='entity',
            name='ClockφLastYear',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='entity',
            name='ClockφSecondLastYear',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='entity',
            name='ClockφThirdLastYear',
            field=models.FloatField(default=0),
        ),
    ]
