# Generated by Django 3.1.4 on 2021-05-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0182_auto_20210524_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='ClockφFourthLastYear',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entity',
            name='ClockφLastYear',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entity',
            name='ClockφSecondLastYear',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entity',
            name='ClockφThirdLastYear',
            field=models.IntegerField(default=0),
        ),
    ]
