# Generated by Django 3.1.4 on 2021-05-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0183_auto_20210524_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='CommonShareIntrinsicValueFourthLastYear',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='entity',
            name='CommonShareIntrinsicValueLastYear',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='entity',
            name='CommonShareIntrinsicValueSecondLastYear',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='entity',
            name='CommonShareIntrinsicValueThirdLastYear',
            field=models.FloatField(default=0),
        ),
    ]
