# Generated by Django 3.1.4 on 2021-05-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0185_auto_20210524_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='ClockφFourthLastYear',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='ClockφLastYear',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='ClockφSecondLastYear',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='ClockφThirdLastYear',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='CommonShareIntrinsicValueFourthLastYear',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='CommonShareIntrinsicValueLastYear',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='CommonShareIntrinsicValueSecondLastYear',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='CommonShareIntrinsicValueThirdLastYear',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='CommonSharePriceFourthLastYear',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='CommonSharePriceLastYear',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='CommonSharePriceSecondLastYear',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='CommonSharePriceThirdLastYear',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='CommonSharesIntrinsicValueFourthLastYear',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='CommonSharesIntrinsicValueLastYear',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='CommonSharesIntrinsicValueSecondLastYear',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='CommonSharesIntrinsicValueThirdLastYear',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='CommonSharesOutstandingFourthLastYear',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='CommonSharesOutstandingLastYear',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='CommonSharesOutstandingSecondLastYear',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='CommonSharesOutstandingThirdLastYear',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='MarketCapitalizationFourthLastYear',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='MarketCapitalizationLastYear',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='MarketCapitalizationSecondLastYear',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='MarketCapitalizationThirdLastYear',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
