# Generated by Django 3.1.4 on 2021-05-26 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0187_auto_20210525_1759'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Puck',
        ),
    ]
