# Generated by Django 3.1.4 on 2021-05-26 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0188_delete_puck'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnomalyFinancingActivitiesSEC',
        ),
    ]
