# Generated by Django 3.1.4 on 2021-05-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0189_delete_anomalyfinancingactivitiessec'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyFinancingActivitiesSEC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
