# Generated by Django 3.1.4 on 2021-05-26 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0190_anomalyfinancingactivitiessec'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnomalyAssets',
        ),
        migrations.DeleteModel(
            name='AnomalyCurrentAssets',
        ),
        migrations.DeleteModel(
            name='AnomalyCurrentAssetsSEC',
        ),
        migrations.DeleteModel(
            name='AnomalyCurrentLiabilities',
        ),
        migrations.DeleteModel(
            name='AnomalyCurrentLiabilitiesSEC',
        ),
        migrations.DeleteModel(
            name='AnomalyFinancingActivities',
        ),
        migrations.DeleteModel(
            name='AnomalyFinancingActivitiesSEC',
        ),
        migrations.DeleteModel(
            name='AnomalyGrossMargin',
        ),
        migrations.DeleteModel(
            name='AnomalyIncomeBeforeTaxes',
        ),
        migrations.DeleteModel(
            name='AnomalyInvestingActivities',
        ),
        migrations.DeleteModel(
            name='AnomalyInvestingActivitiesSEC',
        ),
        migrations.DeleteModel(
            name='AnomalyLiabilities',
        ),
        migrations.DeleteModel(
            name='AnomalyLiabilitiesAndShareholdersEquity',
        ),
        migrations.DeleteModel(
            name='AnomalyNetIncome',
        ),
        migrations.DeleteModel(
            name='AnomalyNonCurrentAssets',
        ),
        migrations.DeleteModel(
            name='AnomalyNonCurrentAssetsSEC',
        ),
        migrations.DeleteModel(
            name='AnomalyNonCurrentLiabilities',
        ),
        migrations.DeleteModel(
            name='AnomalyNonCurrentLiabilitiesSEC',
        ),
        migrations.DeleteModel(
            name='AnomalyOperatingActivities',
        ),
        migrations.DeleteModel(
            name='AnomalyOperatingActivitiesSEC',
        ),
        migrations.DeleteModel(
            name='AnomalyOperatingExpenses',
        ),
        migrations.DeleteModel(
            name='AnomalyOperatingIncome',
        ),
        migrations.DeleteModel(
            name='AnomalyOtherComprehensiveIncome',
        ),
        migrations.DeleteModel(
            name='AnomalyShareholdersEquity',
        ),
        migrations.DeleteModel(
            name='AnomalyShareholdersEquitySEC',
        ),
    ]
