# Generated by Django 3.1.4 on 2021-05-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0191_auto_20210525_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyAccumulatedOtherComprehensiveIncomeGL_i',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyAccumulatedOtherComprehensiveIncomeGL_ii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyAccumulatedOtherComprehensiveIncomeGL_iii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyAccumulatedOtherComprehensiveIncomeValue_i',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyAccumulatedOtherComprehensiveIncomeValue_ii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyAccumulatedOtherComprehensiveIncomeValue_iii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyCommonSharesGL_i',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyCommonSharesGL_ii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyCommonSharesGL_iii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyCommonSharesValue_i',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyCommonSharesValue_ii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyCommonSharesValue_iii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyConvertibleDebtGL_i',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyConvertibleDebtGL_ii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyConvertibleDebtGL_iii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyConvertibleDebtValue_i',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyConvertibleDebtValue_ii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyConvertibleDebtValue_iii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyCurrentAssetsGL_i',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyCurrentAssetsGL_ii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyCurrentAssetsGL_iii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyCurrentAssetsValue_i',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyCurrentAssetsValue_ii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyCurrentAssetsValue_iii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyCurrentLiabilitiesGL_i',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyCurrentLiabilitiesGL_ii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyCurrentLiabilitiesGL_iii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyCurrentLiabilitiesValue_i',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyCurrentLiabilitiesValue_ii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyCurrentLiabilitiesValue_iii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyEmployeeBenefitTrustGL_i',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyEmployeeBenefitTrustGL_ii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyEmployeeBenefitTrustGL_iii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyEmployeeBenefitTrustValue_i',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyEmployeeBenefitTrustValue_ii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyEmployeeBenefitTrustValue_iii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyFinancingActivitiesGL_i',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyFinancingActivitiesGL_ii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyFinancingActivitiesGL_iii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyFinancingActivitiesValue_i',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyFinancingActivitiesValue_ii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyFinancingActivitiesValue_iii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyGrossMarginGL_i',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyGrossMarginGL_ii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyGrossMarginGL_iii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyGrossMarginValue_i',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyGrossMarginValue_ii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyGrossMarginValue_iii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyIncomeBeforeTaxesGL_i',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyIncomeBeforeTaxesGL_ii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyIncomeBeforeTaxesGL_iii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyIncomeBeforeTaxesValue_i',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyIncomeBeforeTaxesValue_ii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyIncomeBeforeTaxesValue_iii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyInvestingActivitiesGL_i',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyInvestingActivitiesGL_ii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyInvestingActivitiesGL_iii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyInvestingActivitiesValue_i',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyInvestingActivitiesValue_ii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyInvestingActivitiesValue_iii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyNetIncomeGL_i',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyNetIncomeGL_ii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyNetIncomeGL_iii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyNetIncomeValue_i',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyNetIncomeValue_ii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyNetIncomeValue_iii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyNonControllingInterestsGL_i',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyNonControllingInterestsGL_ii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyNonControllingInterestsGL_iii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyNonControllingInterestsValue_i',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyNonControllingInterestsValue_ii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyNonControllingInterestsValue_iii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyNonCurrentAssetsGL_i',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyNonCurrentAssetsGL_ii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyNonCurrentAssetsGL_iii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyNonCurrentAssetsValue_i',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyNonCurrentAssetsValue_ii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyNonCurrentAssetsValue_iii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyNonCurrentLiabilitiesGL_i',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyNonCurrentLiabilitiesGL_ii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyNonCurrentLiabilitiesGL_iii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyNonCurrentLiabilitiesValue_i',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyNonCurrentLiabilitiesValue_ii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyNonCurrentLiabilitiesValue_iii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyOperatingActivitiesGL_i',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyOperatingActivitiesGL_ii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyOperatingActivitiesGL_iii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyOperatingActivitiesValue_i',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyOperatingActivitiesValue_ii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyOperatingActivitiesValue_iii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyOperatingExpensesGL_i',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyOperatingExpensesGL_ii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyOperatingExpensesGL_iii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyOperatingExpensesValue_i',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyOperatingExpensesValue_ii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyOperatingExpensesValue_iii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyOperatingIncomeGL_i',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyOperatingIncomeGL_ii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyOperatingIncomeGL_iii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyOperatingIncomeValue_i',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyOperatingIncomeValue_ii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyOperatingIncomeValue_iii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyOtherComprehensiveIncomeGL_i',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyOtherComprehensiveIncomeGL_ii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyOtherComprehensiveIncomeGL_iii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyOtherComprehensiveIncomeValue_i',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyOtherComprehensiveIncomeValue_ii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyOtherComprehensiveIncomeValue_iii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyRetainedEarningsGL_i',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyRetainedEarningsGL_ii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyRetainedEarningsGL_iii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyRetainedEarningsValue_i',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyRetainedEarningsValue_ii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyRetainedEarningsValue_iii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyShareholdersEquityGL_i',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyShareholdersEquityGL_ii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyShareholdersEquityGL_iii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyShareholdersEquityValue_i',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyShareholdersEquityValue_ii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyShareholdersEquityValue_iii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyTreasurySharesGL_i',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyTreasurySharesGL_ii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyTreasurySharesGL_iii',
            field=models.CharField(default=0, max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyTreasurySharesValue_i',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyTreasurySharesValue_ii',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='AnomalyTreasurySharesValue_iii',
            field=models.IntegerField(default=0),
        ),
    ]
