# Generated by Django 3.1.4 on 2021-05-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0192_auto_20210525_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyAccumulatedOtherComprehensiveIncomeGL_i',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyAccumulatedOtherComprehensiveIncomeGL_ii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyAccumulatedOtherComprehensiveIncomeGL_iii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyCommonSharesGL_i',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyCommonSharesGL_ii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyCommonSharesGL_iii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyConvertibleDebtGL_i',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyConvertibleDebtGL_ii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyConvertibleDebtGL_iii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyCurrentAssetsGL_i',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyCurrentAssetsGL_ii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyCurrentAssetsGL_iii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyCurrentLiabilitiesGL_i',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyCurrentLiabilitiesGL_ii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyCurrentLiabilitiesGL_iii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyEmployeeBenefitTrustGL_i',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyEmployeeBenefitTrustGL_ii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyEmployeeBenefitTrustGL_iii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyFinancingActivitiesGL_i',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyFinancingActivitiesGL_ii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyFinancingActivitiesGL_iii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyGrossMarginGL_i',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyGrossMarginGL_ii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyGrossMarginGL_iii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyIncomeBeforeTaxesGL_i',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyIncomeBeforeTaxesGL_ii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyIncomeBeforeTaxesGL_iii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyInvestingActivitiesGL_i',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyInvestingActivitiesGL_ii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyInvestingActivitiesGL_iii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyNetIncomeGL_i',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyNetIncomeGL_ii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyNetIncomeGL_iii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyNonControllingInterestsGL_i',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyNonControllingInterestsGL_ii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyNonControllingInterestsGL_iii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyNonCurrentAssetsGL_i',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyNonCurrentAssetsGL_ii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyNonCurrentAssetsGL_iii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyNonCurrentLiabilitiesGL_i',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyNonCurrentLiabilitiesGL_ii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyNonCurrentLiabilitiesGL_iii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyOperatingActivitiesGL_i',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyOperatingActivitiesGL_ii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyOperatingActivitiesGL_iii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyOperatingExpensesGL_i',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyOperatingExpensesGL_ii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyOperatingExpensesGL_iii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyOperatingIncomeGL_i',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyOperatingIncomeGL_ii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyOperatingIncomeGL_iii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyOtherComprehensiveIncomeGL_i',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyOtherComprehensiveIncomeGL_ii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyOtherComprehensiveIncomeGL_iii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyRetainedEarningsGL_i',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyRetainedEarningsGL_ii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyRetainedEarningsGL_iii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyShareholdersEquityGL_i',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyShareholdersEquityGL_ii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyShareholdersEquityGL_iii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyTreasurySharesGL_i',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyTreasurySharesGL_ii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='AnomalyTreasurySharesGL_iii',
            field=models.CharField(default='', max_length=180),
        ),
    ]
