# Generated by Django 3.1.4 on 2021-05-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0193_auto_20210526_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbalance',
            name='ShareBasedCompensationRetainedEarnings',
            field=models.IntegerField(default=0),
        ),
    ]
