# Generated by Django 3.1.4 on 2021-05-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0194_trialbalance_sharebasedcompensationretainedearnings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditdata',
            old_name='increaseDecreaseInCash',
            new_name='IncreaseDecreaseInCash',
        ),
        migrations.AddField(
            model_name='auditdata',
            name='CashFlowCashExplainedDifference',
            field=models.IntegerField(default=0),
        ),
    ]
