# Generated by Django 3.1.4 on 2021-06-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0197_auto_20210528_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditdata',
            old_name='AnomalyCurrentAssetsGL_i',
            new_name='CurrentAssetsGL_i',
        ),
        migrations.RenameField(
            model_name='auditdata',
            old_name='AnomalyCurrentAssetsGL_ii',
            new_name='CurrentAssetsGL_ii',
        ),
        migrations.RenameField(
            model_name='auditdata',
            old_name='AnomalyCurrentAssetsGL_iii',
            new_name='CurrentAssetsGL_iii',
        ),
        migrations.RenameField(
            model_name='auditdata',
            old_name='AnomalyCurrentLiabilitiesGL_i',
            new_name='CurrentLiabilitiesGL_i',
        ),
        migrations.RenameField(
            model_name='auditdata',
            old_name='AnomalyCurrentLiabilitiesGL_ii',
            new_name='CurrentLiabilitiesGL_ii',
        ),
        migrations.RenameField(
            model_name='auditdata',
            old_name='AnomalyCurrentLiabilitiesGL_iii',
            new_name='CurrentLiabilitiesGL_iii',
        ),
        migrations.RenameField(
            model_name='auditdata',
            old_name='AnomalyFinancingActivitiesGL_i',
            new_name='FinancingActivitiesGL_i',
        ),
        migrations.RenameField(
            model_name='auditdata',
            old_name='AnomalyFinancingActivitiesGL_ii',
            new_name='FinancingActivitiesGL_ii',
        ),
        migrations.RenameField(
            model_name='auditdata',
            old_name='AnomalyFinancingActivitiesGL_iii',
            new_name='FinancingActivitiesGL_iii',
        ),
        migrations.RenameField(
            model_name='auditdata',
            old_name='AnomalyGrossMarginGL_i',
            new_name='GrossMarginGL_i',
        ),
        migrations.RenameField(
            model_name='auditdata',
            old_name='AnomalyGrossMarginGL_ii',
            new_name='GrossMarginGL_ii',
        ),
        migrations.RenameField(
            model_name='auditdata',
            old_name='AnomalyGrossMarginGL_iii',
            new_name='GrossMarginGL_iii',
        ),
        migrations.RenameField(
            model_name='auditdata',
            old_name='AnomalyIncomeBeforeTaxesGL_i',
            new_name='IncomeBeforeTaxesGL_i',
        ),
        migrations.RenameField(
            model_name='auditdata',
            old_name='AnomalyIncomeBeforeTaxesGL_ii',
            new_name='IncomeBeforeTaxesGL_ii',
        ),
        migrations.RenameField(
            model_name='auditdata',
            old_name='AnomalyIncomeBeforeTaxesGL_iii',
            new_name='IncomeBeforeTaxesGL_iii',
        ),
        migrations.RenameField(
            model_name='auditdata',
            old_name='AnomalyInvestingActivitiesGL_i',
            new_name='InvestingActivitiesGL_i',
        ),
        migrations.RenameField(
            model_name='auditdata',
            old_name='AnomalyInvestingActivitiesGL_ii',
            new_name='InvestingActivitiesGL_ii',
        ),
        migrations.RenameField(
            model_name='auditdata',
            old_name='AnomalyInvestingActivitiesGL_iii',
            new_name='InvestingActivitiesGL_iii',
        ),
        migrations.RenameField(
            model_name='auditdata',
            old_name='AnomalyNetIncomeGL_i',
            new_name='NetIncomeGL_i',
        ),
        migrations.RenameField(
            model_name='auditdata',
            old_name='AnomalyNetIncomeGL_ii',
            new_name='NetIncomeGL_ii',
        ),
        migrations.RenameField(
            model_name='auditdata',
            old_name='AnomalyNetIncomeGL_iii',
            new_name='NetIncomeGL_iii',
        ),
        migrations.RenameField(
            model_name='auditdata',
            old_name='AnomalyNonCurrentAssetsGL_i',
            new_name='NonCurrentAssetsGL_i',
        ),
        migrations.RenameField(
            model_name='auditdata',
            old_name='AnomalyNonCurrentAssetsGL_ii',
            new_name='NonCurrentAssetsGL_ii',
        ),
        migrations.RenameField(
            model_name='auditdata',
            old_name='AnomalyNonCurrentAssetsGL_iii',
            new_name='NonCurrentAssetsGL_iii',
        ),
        migrations.RemoveField(
            model_name='auditdata',
            name='AnomalyNonCurrentLiabilitiesGL_i',
        ),
        migrations.RemoveField(
            model_name='auditdata',
            name='AnomalyNonCurrentLiabilitiesGL_ii',
        ),
        migrations.RemoveField(
            model_name='auditdata',
            name='AnomalyNonCurrentLiabilitiesGL_iii',
        ),
        migrations.RemoveField(
            model_name='auditdata',
            name='AnomalyOperatingActivitiesGL_i',
        ),
        migrations.RemoveField(
            model_name='auditdata',
            name='AnomalyOperatingActivitiesGL_ii',
        ),
        migrations.RemoveField(
            model_name='auditdata',
            name='AnomalyOperatingActivitiesGL_iii',
        ),
        migrations.RemoveField(
            model_name='auditdata',
            name='AnomalyOperatingExpensesGL_i',
        ),
        migrations.RemoveField(
            model_name='auditdata',
            name='AnomalyOperatingExpensesGL_ii',
        ),
        migrations.RemoveField(
            model_name='auditdata',
            name='AnomalyOperatingExpensesGL_iii',
        ),
        migrations.RemoveField(
            model_name='auditdata',
            name='AnomalyOperatingIncomeGL_i',
        ),
        migrations.RemoveField(
            model_name='auditdata',
            name='AnomalyOperatingIncomeGL_ii',
        ),
        migrations.RemoveField(
            model_name='auditdata',
            name='AnomalyOperatingIncomeGL_iii',
        ),
        migrations.RemoveField(
            model_name='auditdata',
            name='AnomalyOtherComprehensiveIncomeGL_i',
        ),
        migrations.RemoveField(
            model_name='auditdata',
            name='AnomalyOtherComprehensiveIncomeGL_ii',
        ),
        migrations.RemoveField(
            model_name='auditdata',
            name='AnomalyOtherComprehensiveIncomeGL_iii',
        ),
        migrations.RemoveField(
            model_name='auditdata',
            name='AnomalyShareholdersEquityBalanceGL_i',
        ),
        migrations.RemoveField(
            model_name='auditdata',
            name='AnomalyShareholdersEquityBalanceGL_ii',
        ),
        migrations.RemoveField(
            model_name='auditdata',
            name='AnomalyShareholdersEquityBalanceGL_iii',
        ),
        migrations.RemoveField(
            model_name='auditdata',
            name='AnomalyShareholdersEquityGL_i',
        ),
        migrations.RemoveField(
            model_name='auditdata',
            name='AnomalyShareholdersEquityGL_ii',
        ),
        migrations.RemoveField(
            model_name='auditdata',
            name='AnomalyShareholdersEquityGL_iii',
        ),
        migrations.AddField(
            model_name='auditdata',
            name='NonCurrentLiabilitiesGL_i',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='NonCurrentLiabilitiesGL_ii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='NonCurrentLiabilitiesGL_iii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='OperatingActivitiesGL_i',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='OperatingActivitiesGL_ii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='OperatingActivitiesGL_iii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='OperatingExpensesGL_i',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='OperatingExpensesGL_ii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='OperatingExpensesGL_iii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='OperatingIncomeGL_i',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='OperatingIncomeGL_ii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='OperatingIncomeGL_iii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='OtherComprehensiveIncomeGL_i',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='OtherComprehensiveIncomeGL_ii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='OtherComprehensiveIncomeGL_iii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='ShareholdersEquityBalanceGL_i',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='ShareholdersEquityBalanceGL_ii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='ShareholdersEquityBalanceGL_iii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='ShareholdersEquityGL_i',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='ShareholdersEquityGL_ii',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='ShareholdersEquityGL_iii',
            field=models.CharField(default='', max_length=180),
        ),
    ]
