# Generated by Django 3.1.4 on 2021-09-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0198_auto_20210601_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdata',
            name='NormalizedDividendPaymentToNonControllingInterests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='NormalizedDividendPaymentToPreferredShareholders',
            field=models.IntegerField(default=0),
        ),
    ]
