# Generated by Django 3.1.4 on 2021-09-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0201_auto_20210916_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditdata',
            name='TargetWorkingCapital',
            field=models.FloatField(default=1.2),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='TheoricalTaxRate',
            field=models.FloatField(default=0.25),
        ),
    ]
