# Generated by Django 3.1.4 on 2021-09-16 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0202_auto_20210916_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditdata',
            name='TargetWorkingCapital',
        ),
    ]
