# Generated by Django 3.1.4 on 2021-09-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0203_remove_auditdata_targetworkingcapital'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdata',
            name='TargetWorkingCapital',
            field=models.FloatField(default=1.2),
        ),
    ]
