# Generated by Django 3.1.4 on 2021-09-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0204_auditdata_targetworkingcapital'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdata',
            name='CapitalizationRateFloor',
            field=models.FloatField(default=0.021),
        ),
    ]
