# Generated by Django 3.1.4 on 2021-09-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0205_auditdata_capitalizationratefloor'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdata',
            name='ReinvestmentOfMaintenance',
            field=models.IntegerField(default=0),
        ),
    ]
