# Generated by Django 3.1.4 on 2021-09-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0206_auditdata_reinvestmentofmaintenance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditdata',
            old_name='ReinvestmentOfMaintenance',
            new_name='HistoricalReinvestmentOfMaintenance',
        ),
    ]
