# Generated by Django 3.1.4 on 2021-09-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('φ', '0208_auto_20210919_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditdata',
            name='NormalizedTheoricalInterestCharge',
        ),
        migrations.AddField(
            model_name='auditdata',
            name='TheoricalInterestRate',
            field=models.IntegerField(default=0.035),
        ),
    ]
